### PR TITLE
Benchmarks raw data

### PR DESCRIPTION
**Pull request by pavankum**
Raw data for QM benchmarks and some updates to the compute-metrics and plotting-metrics scripts.

### CODE REVIEW

**Comment by mattwthompson** [comment]
Ha! First time I've seen this:

image

**Comment by j-wags** [comment]
Since merging this would clutter up the repo, maybe it'd be better to add it as a release asset. I've offered you write access to this repo, @pavankum - The link to accept it is [here](https://github.com/openforcefield/openff-sage/invitations). Then you should be able to upload a tarball of the files as release assets by editing the release entry [here](https://github.com/openforcefield/openff-sage/releases). If this is your first time adding release assets I'd be happy to screenshare and walk you through it.

**Comment by j-wags** [comment]
We've added this info to the release assets, so I'm closing this PR.

**Comment by jchodera** [comment]
Thanks!

**Pull request closed without merging**
